- platform: darksky
  api_key: !secret DARKSKY_API_KEY
  monitored_conditions:
    - summary
    - precip_probability
    - temperature
    - humidity
    - pressure
    - visibility
    - wind_speed
