- platform: template
  sensors:
    garage_door:
      value_template: > 
        {% if is_state('sensor.esp165a0c_distance', 'unknown') %} Unknown
        {% elif states('sensor.esp165a0c_distance') | float > 18.5 %} Closed
        {% else %} Open
        {% endif %}
      entity_id:
        sensor.esp165a0c_distance